### ISSUE TITLE
Performance benchmarks in README

### ISSUE THREAD

**Issue by danielbayley** [fabiospampinato/tiny-readdir-glob#2]
As mentioned in https://github.com/sindresorhus/globby/issues/50#issuecomment-2030987298, given so many glob packages around, it would be useful to see how this performs against others, and in particular _[`fdir`](https://github.com/thecodrr/fdir)_… Maybe this could take the form of a table in the README?

**Comment by fabiospampinato** [comment]
I don't want to keep the numbers in the readme up to date, but for this:

```ts
import { fdir } from 'fdir';
import readdir from 'tiny-readdir-glob';
import process from 'node:process';

console.time('fdir');
const files1 = await new fdir().withFullPaths().glob(['./**/*.js']).crawl(process.cwd()).withPromise();
console.timeEnd('fdir');

console.time('tiny-readdyr-glob');
const { files: files2 } = await readdir(['**/*.js'], { cwd: process.cwd() });
console.timeEnd('tiny-readdyr-glob');

console.log(files1.length);
console.log(files2.length);
```

I see this:

<img width="1060" alt="Screen Shot 2024-04-02 at 16 38 21" src="https://github.com/fabiospampinato/tiny-readdir-glob/assets/1812093/fb677228-3047-460c-9d4f-01dd154d0dd7">

So `fdir` seems slightly faster here. It's not exactly a super fair test as `fdir` is returning me file paths, while mine is returning me a lot more information potentially. Also if I change the glob to `node_modules/**/*.js` or `./node_modules/**/*.js` then `fdir` doesn't find anything for some reason, and optimizing those kind of globs is kinda `tiny-readdir-glob`'s whole point.
